cd c:\xampp\php
php.exe -f c:\xampp\htdocs\HCMP\index.php rtk_management partner_detailed_summary 1
php.exe -f c:\xampp\htdocs\HCMP\index.php rtk_management partner_detailed_summary 2
php.exe -f c:\xampp\htdocs\HCMP\index.php rtk_management partner_detailed_summary 3
php.exe -f c:\xampp\htdocs\HCMP\index.php rtk_management partner_detailed_summary 4
php.exe -f c:\xampp\htdocs\HCMP\index.php rtk_management partner_detailed_summary 5
php.exe -f c:\xampp\htdocs\HCMP\index.php rtk_management partner_detailed_summary 6
php.exe -f c:\xampp\htdocs\HCMP\index.php rtk_management partner_detailed_summary 7
php.exe -f c:\xampp\htdocs\HCMP\index.php rtk_management partner_detailed_summary 8
php.exe -f c:\xampp\htdocs\HCMP\index.php rtk_management partner_detailed_summary 9
php.exe -f c:\xampp\htdocs\HCMP\index.php rtk_management partner_detailed_summary 10
php.exe -f c:\xampp\htdocs\HCMP\index.php rtk_management partner_detailed_summary 11
php.exe -f c:\xampp\htdocs\HCMP\index.php rtk_management partner_detailed_summary 12
php.exe -f c:\xampp\htdocs\HCMP\index.php rtk_management partner_detailed_summary 13
php.exe -f c:\xampp\htdocs\HCMP\index.php rtk_management partner_detailed_summary 14
php.exe -f c:\xampp\htdocs\HCMP\index.php rtk_management partner_detailed_summary 15
php.exe -f c:\xampp\htdocs\HCMP\index.php rtk_management partner_detailed_summary 16
php.exe -f c:\xampp\htdocs\HCMP\index.php rtk_management partner_detailed_summary 17
php.exe -f c:\xampp\htdocs\HCMP\index.php rtk_management partner_detailed_summary 18
php.exe -f c:\xampp\htdocs\HCMP\index.php rtk_management partner_detailed_summary 19
php.exe -f c:\xampp\htdocs\HCMP\index.php rtk_management partner_detailed_summary 20
php.exe -f c:\xampp\htdocs\HCMP\index.php rtk_management partner_detailed_summary 21
php.exe -f c:\xampp\htdocs\HCMP\index.php rtk_management partner_detailed_summary 22
php.exe -f c:\xampp\htdocs\HCMP\index.php rtk_management partner_detailed_summary 23
php.exe -f c:\xampp\htdocs\HCMP\index.php rtk_management partner_detailed_summary 24
php.exe -f c:\xampp\htdocs\HCMP\index.php rtk_management partner_detailed_summary 25
php.exe -f c:\xampp\htdocs\HCMP\index.php rtk_management partner_detailed_summary 26
php.exe -f c:\xampp\htdocs\HCMP\index.php rtk_management partner_detailed_summary 27
php.exe -f c:\xampp\htdocs\HCMP\index.php rtk_management partner_detailed_summary 28
php.exe -f c:\xampp\htdocs\HCMP\index.php rtk_management partner_detailed_summary 29
php.exe -f c:\xampp\htdocs\HCMP\index.php rtk_management partner_detailed_summary 30
